name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm install
        
      - name: Install start-server-and-test
        run: npm install --save-dev start-server-and-test
      
      - name: Test
        run: |
          npx start-server-and-test 'cd server && npm start' http://localhost:3001 'npx cypress run --browser electron'
